version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: lab_06
      POSTGRES_DB: lab_06_production
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  web:
    build: .
    command: bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - localhost
    environment:
      RECIPE_LAB_06_DATABASE_PASSWORD: password
      SECRET_KEY_BASE: 229bee1d0c5a5c4e650a9761919bf85d7c9d9b36e00cc4d812cd05b1de67c51b8c841554d68a409b3d3d72f3eff9a58909aaef1e550c0a2eac44060ac53abeea

volumes:
  pgdata: